In [1]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
import datetime

In [96]:
pd.set_option('display.max_columns', 25)
pd.set_option('display.max_rows', 175)
pd.set_option('display.precision', 3)

In [3]:
# Source: http://web.mta.info/developers/turnstile.html
def get_data(week_nums):
    # base url
    url = "http://web.mta.info/developers/data/nyct/turnstile/turnstile_{}.txt"
    dfs = []
    for week_num in week_nums:
        # concat our week onto url.. 
        file_url = url.format(week_num)
        dfs.append(pd.read_csv(file_url))
    return pd.concat(dfs)
        
week_nums = [170527, 170520, 170513, 170506, 170429]
df = get_data(week_nums)

In [4]:
len(df)

983349

In [5]:
df.reset_index()

,index,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,00:00:00,REGULAR,6184841,2095161
1,1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167
2,2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192
3,3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275
4,4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326
5,5,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,20:00:00,REGULAR,6185506,2095379
6,6,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,00:00:00,REGULAR,6185634,2095402
7,7,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,04:00:00,REGULAR,6185655,2095410
8,8,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,08:00:00,REGULAR,6185665,2095420
9,9,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,12:00:00,REGULAR,6185734,2095480
10,10,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,16:00:00,REGULAR,6185889,2095539
11,11,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/21/2017,20:00:00,REGULAR,6186111,2095577
12,12,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/22/2017,00:00:00,REGULAR,6186215,2095600
13,13,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/22/2017,08:00:00,REGULAR,6186282,2095704
14,14,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/22/2017,12:00:00,REGULAR,6186432,2095955
15,15,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/22/2017,16:00:00,REGULAR,6186689,2096029
16,16,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/22/2017,20:00:00,REGULAR,6187464,2096100
...,...,...,...,...,...,...,...,...,...,...,...,...
983332,198243,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/26/2017,05:00:00,REGULAR,5554,297
983333,198244,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/26/2017,09:00:00,REGULAR,5554,297
983334,198245,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/26/2017,13:00:00,REGULAR,5554,297
983335,198246,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/26/2017,17:00:00,REGULAR,5554,297
983336,198247,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/26/2017,21:00:00,REGULAR,5554,297
983337,198248,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,01:00:00,REGULAR,5554,297
983338,198249,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,05:00:00,REGULAR,5554,297
983339,198250,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,09:00:00,REGULAR,5554,297
983340,198251,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,13:00:00,REGULAR,5554,297
983341,198252,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,17:00:00,REGULAR,5554,297
983342,198253,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/27/2017,21:00:00,REGULAR,5554,297
983343,198254,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,01:00:00,REGULAR,5554,297
983344,198255,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,05:00:00,REGULAR,5554,297
983345,198256,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,09:00:00,REGULAR,5554,297
983346,198257,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,13:00:00,REGULAR,5554,297
983347,198258,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,17:00:00,REGULAR,5554,297
983348,198259,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,04/28/2017,21:00:00,REGULAR,5554,297

In [6]:
df.rename(columns=lambda x: x.strip(), inplace=True)

In [7]:
df['LINESORT'] = df.LINENAME.apply(sorted)

In [8]:
df['LINESORT'] = df.LINESORT.apply(''.join)

In [9]:
df['STAT_MERGE'] = df['STATION'] + ' ' + df['LINESORT']

In [10]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,00:00:00,REGULAR,6184841,2095161,456NQRW,59 ST 456NQRW
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW

In [11]:
df['ACTUALENTRY'] = df['ENTRIES'].diff()
mask = df.UNIT != df.UNIT.shift(1)
mask2 = df.SCP != df.SCP.shift(1)
df['ACTUALENTRY'][mask] = np.nan
df['ACTUALENTRY'][mask2] = np.nan

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [12]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,00:00:00,REGULAR,6184841,2095161,456NQRW,59 ST 456NQRW,NaN
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0

In [13]:
df['ACTUALEXIT'] = df['EXITS'].diff()
df['ACTUALEXIT'][mask] = np.nan
df['ACTUALEXIT'][mask2] = np.nan

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,00:00:00,REGULAR,6184841,2095161,456NQRW,59 ST 456NQRW,NaN,NaN
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0,6.0
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0,25.0
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0,83.0
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0,51.0

In [15]:
df["DATE_TIME"] = pd.to_datetime(df.DATE + " " +df.TIME, format="%m/%d/%Y %H:%M:%S")

In [16]:
df['TIMEDIFF'] = df['DATE_TIME'].diff()
mask = df.UNIT != df.UNIT.shift(1)
mask2 = df.SCP != df.SCP.shift(1)
df['TIMEDIFF'][mask] = np.nan
df['TIMEDIFF'][mask2] = np.nan

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [17]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,00:00:00,REGULAR,6184841,2095161,456NQRW,59 ST 456NQRW,NaN,NaN,2017-05-20 00:00:00,NaT
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0,6.0,2017-05-20 04:00:00,04:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0,25.0,2017-05-20 08:00:00,04:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0,83.0,2017-05-20 12:00:00,04:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0,51.0,2017-05-20 16:00:00,04:00:00

In [18]:
df.TIMEDIFF.value_counts()

0 days 04:00:00    885116
0 days 04:12:00     60545
0 days 08:00:00      1139
0 days 04:26:00       717
0 days 00:01:20       370
0 days 00:01:21       198
0 days 00:01:33        75
0 days 04:11:59        68
0 days 00:01:41        59
0 days 00:01:07        59
0 days 00:01:25        53
0 days 00:01:31        47
0 days 00:01:05        45
0 days 00:01:22        45
0 days 00:01:36        42
0 days 00:00:26        37
0 days 00:01:15        37
                    ...
0 days 08:13:17         1
0 days 04:04:48         1
0 days 04:13:17         1
0 days 01:53:28         1
0 days 04:02:01         1
0 days 04:02:15         1
0 days 04:06:36         1
0 days 04:45:47         1
0 days 04:17:54         1
0 days 04:07:51         1
0 days 04:01:18         1
0 days 04:10:29         1
0 days 04:08:34         1
0 days 04:53:46         1
1 days 04:17:54         1
0 days 04:12:12         1
0 days 02:08:17         1
Name: TIMEDIFF, Length: 2166, dtype: int64

In [19]:
df.TIME.value_counts().head(20)

04:00:00    84016
00:00:00    84010
20:00:00    83949
08:00:00    83943
16:00:00    83914
12:00:00    83910
05:00:00    60546
01:00:00    60530
17:00:00    60505
09:00:00    60474
21:00:00    60465
13:00:00    60450
18:00:00     3846
06:00:00     3841
10:00:00     3837
02:00:00     3836
14:00:00     3834
22:00:00     3833
03:00:00     1370
15:00:00     1370
Name: TIME, dtype: int64

In [20]:
df['ACTUALENTRY'] = abs(df['ACTUALENTRY'])

In [21]:
df['ACTUALEXIT'] = abs(df['ACTUALEXIT'])

In [22]:
df.sort_values(by = 'ACTUALENTRY', ascending=False).head(15)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF
195481,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,05/05/2017,09:00:00,REGULAR,1560221483,1728055978,5,EASTCHSTER/DYRE 5,1.558e+09,1.727e+09,2017-05-05 09:00:00,0 days 20:00:00
151863,R241A,R048,00-00-04,GRD CNTRL-42 ST,4567S,IRT,05/25/2017,09:00:00,REGULAR,95,21,4567S,GRD CNTRL-42 ST 4567S,8.566e+08,5.039e+07,2017-05-25 09:00:00,0 days 20:00:00
135682,R161B,R452,00-00-03,72 ST,123,IRT,04/30/2017,13:00:00,REGULAR,691260128,1758148378,123,72 ST 123,6.832e+08,1.751e+09,2017-04-30 13:00:00,0 days 16:00:00
136323,R169,R168,01-03-01,96 ST,123,IRT,05/25/2017,21:00:00,REGULAR,183,752,123,96 ST 123,6.058e+08,1.313e+09,2017-05-25 21:00:00,0 days 04:00:00
153362,R241A,R048,00-00-00,GRD CNTRL-42 ST,4567S,IRT,05/04/2017,13:00:00,REGULAR,503289886,1207885953,4567S,GRD CNTRL-42 ST 4567S,4.885e+08,1.179e+09,2017-05-04 13:00:00,0 days 04:00:00
134024,R160A,R164,00-05-00,66 ST-LINCOLN,1,IRT,05/19/2017,09:00:00,RECOVR AUD,117440512,0,1,66 ST-LINCOLN 1,1.170e+08,0.000e+00,2017-05-19 09:00:00,0 days 04:00:00
9686,A054,R227,01-06-00,RECTOR ST,NRW,BMT,05/22/2017,20:00:00,REGULAR,371,20,NRW,RECTOR ST NRW,1.008e+08,1.682e+07,2017-05-22 20:00:00,0 days 04:00:00
150431,R228,R143,00-00-04,28 ST,6,IRT,04/26/2017,17:00:00,REGULAR,100710462,33611766,6,28 ST 6,1.004e+08,3.273e+07,2017-04-26 17:00:00,0 days 08:00:00
184715,R602,R108,00-06-01,BOROUGH HALL,2345R,IRT,05/17/2017,08:00:00,REGULAR,117440523,10,2345R,BOROUGH HALL 2345R,9.825e+07,2.064e+06,2017-05-17 08:00:00,0 days 04:00:00
64691,N138,R355,01-06-01,111 ST,A,IND,05/18/2017,13:00:00,REGULAR,83942621,33592614,A,111 ST A,8.356e+07,3.345e+07,2017-05-18 13:00:00,0 days 04:00:00
166407,R311,R053,00-05-00,3 AV-149 ST,25,IRT,04/28/2017,16:00:00,REGULAR,67108864,16777216,25,3 AV-149 ST 25,6.711e+07,1.678e+07,2017-04-28 16:00:00,0 days 04:00:00
160102,R287,R244,00-05-00,BURNSIDE AV,4,IRT,05/26/2017,16:00:00,REGULAR,33554476,6,4,BURNSIDE AV 4,3.083e+07,4.069e+06,2017-05-26 16:00:00,0 days 04:00:00
71940,N223,R156,01-06-01,BEDFORD PK BLVD,BD,IND,05/17/2017,17:00:00,REGULAR,33554676,67,BD,BEDFORD PK BLVD BD,3.050e+07,4.456e+05,2017-05-17 17:00:00,0 days 12:00:00
152949,R240,R047,00-00-01,GRD CNTRL-42 ST,4567S,IRT,05/04/2017,17:00:00,REGULAR,1866,16,4567S,GRD CNTRL-42 ST 4567S,2.024e+07,1.389e+07,2017-05-04 17:00:00,1 days 16:00:00
156880,R251,R144,00-03-02,96 ST,6,IRT,05/19/2017,05:00:00,REGULAR,65804,19,6,96 ST 6,1.940e+07,2.191e+06,2017-05-19 05:00:00,0 days 04:00:00

In [23]:
df = df[df.DESC == 'REGULAR']

In [24]:
df.sort_values(by = 'ACTUALENTRY', ascending=False).head(15)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF
195481,R730,R431,00-00-04,EASTCHSTER/DYRE,5,IRT,05/05/2017,09:00:00,REGULAR,1560221483,1728055978,5,EASTCHSTER/DYRE 5,1.558e+09,1.727e+09,2017-05-05 09:00:00,0 days 20:00:00
151863,R241A,R048,00-00-04,GRD CNTRL-42 ST,4567S,IRT,05/25/2017,09:00:00,REGULAR,95,21,4567S,GRD CNTRL-42 ST 4567S,8.566e+08,5.039e+07,2017-05-25 09:00:00,0 days 20:00:00
135682,R161B,R452,00-00-03,72 ST,123,IRT,04/30/2017,13:00:00,REGULAR,691260128,1758148378,123,72 ST 123,6.832e+08,1.751e+09,2017-04-30 13:00:00,0 days 16:00:00
136323,R169,R168,01-03-01,96 ST,123,IRT,05/25/2017,21:00:00,REGULAR,183,752,123,96 ST 123,6.058e+08,1.313e+09,2017-05-25 21:00:00,0 days 04:00:00
153362,R241A,R048,00-00-00,GRD CNTRL-42 ST,4567S,IRT,05/04/2017,13:00:00,REGULAR,503289886,1207885953,4567S,GRD CNTRL-42 ST 4567S,4.885e+08,1.179e+09,2017-05-04 13:00:00,0 days 04:00:00
9686,A054,R227,01-06-00,RECTOR ST,NRW,BMT,05/22/2017,20:00:00,REGULAR,371,20,NRW,RECTOR ST NRW,1.008e+08,1.682e+07,2017-05-22 20:00:00,0 days 04:00:00
150431,R228,R143,00-00-04,28 ST,6,IRT,04/26/2017,17:00:00,REGULAR,100710462,33611766,6,28 ST 6,1.004e+08,3.273e+07,2017-04-26 17:00:00,0 days 08:00:00
184715,R602,R108,00-06-01,BOROUGH HALL,2345R,IRT,05/17/2017,08:00:00,REGULAR,117440523,10,2345R,BOROUGH HALL 2345R,9.825e+07,2.064e+06,2017-05-17 08:00:00,0 days 04:00:00
64691,N138,R355,01-06-01,111 ST,A,IND,05/18/2017,13:00:00,REGULAR,83942621,33592614,A,111 ST A,8.356e+07,3.345e+07,2017-05-18 13:00:00,0 days 04:00:00
166407,R311,R053,00-05-00,3 AV-149 ST,25,IRT,04/28/2017,16:00:00,REGULAR,67108864,16777216,25,3 AV-149 ST 25,6.711e+07,1.678e+07,2017-04-28 16:00:00,0 days 04:00:00
160102,R287,R244,00-05-00,BURNSIDE AV,4,IRT,05/26/2017,16:00:00,REGULAR,33554476,6,4,BURNSIDE AV 4,3.083e+07,4.069e+06,2017-05-26 16:00:00,0 days 04:00:00
71940,N223,R156,01-06-01,BEDFORD PK BLVD,BD,IND,05/17/2017,17:00:00,REGULAR,33554676,67,BD,BEDFORD PK BLVD BD,3.050e+07,4.456e+05,2017-05-17 17:00:00,0 days 12:00:00
152949,R240,R047,00-00-01,GRD CNTRL-42 ST,4567S,IRT,05/04/2017,17:00:00,REGULAR,1866,16,4567S,GRD CNTRL-42 ST 4567S,2.024e+07,1.389e+07,2017-05-04 17:00:00,1 days 16:00:00
156880,R251,R144,00-03-02,96 ST,6,IRT,05/19/2017,05:00:00,REGULAR,65804,19,6,96 ST 6,1.940e+07,2.191e+06,2017-05-19 05:00:00,0 days 04:00:00
16384,B022,R229,00-05-00,AVENUE M,BQ,BMT,05/01/2017,12:00:00,REGULAR,11,1,BQ,AVENUE M BQ,1.680e+07,2.517e+08,2017-05-01 12:00:00,0 days 04:00:00

In [25]:
new_df = df[df.ACTUALENTRY < 5000]

In [26]:
new_df.sort_values(by = 'ACTUALENTRY', ascending=False).head(15)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF
151644,R240,R047,00-03-08,GRD CNTRL-42 ST,4567S,IRT,05/23/2017,21:00:00,REGULAR,34087044,7650960,4567S,GRD CNTRL-42 ST 4567S,4517.0,322.0,2017-05-23 21:00:00,08:00:00
151834,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/10/2017,20:00:00,REGULAR,28652861,8757415,4567S,GRD CNTRL-42 ST 4567S,4481.0,16.0,2017-05-10 20:00:00,04:00:00
151196,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/16/2017,20:00:00,REGULAR,28683723,8769962,4567S,GRD CNTRL-42 ST 4567S,4310.0,31.0,2017-05-16 20:00:00,04:00:00
150903,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/22/2017,20:00:00,REGULAR,28718908,8784054,4567S,GRD CNTRL-42 ST 4567S,4193.0,11.0,2017-05-22 20:00:00,04:00:00
150909,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/23/2017,20:00:00,REGULAR,28729423,8785878,4567S,GRD CNTRL-42 ST 4567S,4173.0,32.0,2017-05-23 20:00:00,04:00:00
151828,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/09/2017,20:00:00,REGULAR,28643321,8754658,4567S,GRD CNTRL-42 ST 4567S,4051.0,147.0,2017-05-09 20:00:00,04:00:00
150915,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/24/2017,20:00:00,REGULAR,28740872,8787664,4567S,GRD CNTRL-42 ST 4567S,4051.0,91.0,2017-05-24 20:00:00,04:00:00
151275,R240,R047,00-00-01,GRD CNTRL-42 ST,4567S,IRT,05/23/2017,21:00:00,REGULAR,78792,81397,4567S,GRD CNTRL-42 ST 4567S,4009.0,1064.0,2017-05-23 21:00:00,08:00:00
151845,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/12/2017,20:00:00,REGULAR,28667816,8764388,4567S,GRD CNTRL-42 ST 4567S,4007.0,17.0,2017-05-12 20:00:00,04:00:00
90084,N420B,R317,00-00-01,CLINTON-WASH AV,G,IND,05/06/2017,21:00:00,REGULAR,7,10,G,CLINTON-WASH AV G,3962.0,7368.0,2017-05-06 21:00:00,04:00:00
153112,R238,R046,00-00-06,GRD CNTRL-42 ST,4567S,IRT,04/25/2017,20:00:00,REGULAR,3452499,7554652,4567S,GRD CNTRL-42 ST 4567S,3961.0,64.0,2017-04-25 20:00:00,04:00:00
151839,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/11/2017,20:00:00,REGULAR,28659909,8760842,4567S,GRD CNTRL-42 ST 4567S,3956.0,123.0,2017-05-11 20:00:00,04:00:00
151748,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,05/10/2017,20:00:00,REGULAR,13522703,5043784,4567S,GRD CNTRL-42 ST 4567S,3890.0,436.0,2017-05-10 20:00:00,04:00:00
151214,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/19/2017,20:00:00,REGULAR,28708076,8778147,4567S,GRD CNTRL-42 ST 4567S,3863.0,40.0,2017-05-19 20:00:00,04:00:00
150921,R238,R046,00-03-02,GRD CNTRL-42 ST,4567S,IRT,05/25/2017,20:00:00,REGULAR,28749882,8790104,4567S,GRD CNTRL-42 ST 4567S,3840.0,156.0,2017-05-25 20:00:00,04:00:00

In [27]:
new_df = df[df.ACTUALEXIT < 5000]

In [28]:
new_df.sort_values(by = 'ACTUALEXIT', ascending=False).head(15)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF
49024,N063A,R011,00-00-00,42 ST-PORT AUTH,ACENQRS1237W,IND,05/22/2017,20:00:00,REGULAR,16459422,57736969,1237ACENQRSW,42 ST-PORT AUTH 1237ACENQRSW,68.0,4888.0,2017-05-22 20:00:00,04:00:00
153200,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,04/26/2017,12:00:00,REGULAR,13464905,4960372,4567S,GRD CNTRL-42 ST 4567S,677.0,4876.0,2017-04-26 12:00:00,04:00:00
153206,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,04/27/2017,12:00:00,REGULAR,13469687,4973876,4567S,GRD CNTRL-42 ST 4567S,705.0,4870.0,2017-04-27 12:00:00,04:00:00
153194,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,04/25/2017,12:00:00,REGULAR,13462328,4945957,4567S,GRD CNTRL-42 ST 4567S,656.0,4868.0,2017-04-25 12:00:00,04:00:00
153250,R238,R046,00-03-01,GRD CNTRL-42 ST,4567S,IRT,04/27/2017,20:00:00,REGULAR,17952071,7090305,4567S,GRD CNTRL-42 ST 4567S,0.0,4850.0,2017-04-27 20:00:00,04:00:00
50046,N063A,R011,00-00-01,42 ST-PORT AUTH,ACENQRS1237W,IND,04/25/2017,20:00:00,REGULAR,1277656019,171923490,1237ACENQRSW,42 ST-PORT AUTH 1237ACENQRSW,84.0,4828.0,2017-04-25 20:00:00,04:00:00
153188,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,04/24/2017,12:00:00,REGULAR,13459363,4932189,4567S,GRD CNTRL-42 ST 4567S,670.0,4811.0,2017-04-24 12:00:00,04:00:00
49048,N063A,R011,00-00-00,42 ST-PORT AUTH,ACENQRS1237W,IND,05/25/2017,20:00:00,REGULAR,16467346,57767033,1237ACENQRSW,42 ST-PORT AUTH 1237ACENQRSW,75.0,4797.0,2017-05-25 20:00:00,04:00:00
153357,R241A,R048,00-00-00,GRD CNTRL-42 ST,4567S,IRT,05/03/2017,13:00:00,REGULAR,14838373,28874837,4567S,GRD CNTRL-42 ST 4567S,0.0,4589.0,2017-05-03 13:00:00,08:00:00
152199,R238,R046,00-03-01,GRD CNTRL-42 ST,4567S,IRT,05/01/2017,20:00:00,REGULAR,17965030,7132642,4567S,GRD CNTRL-42 ST 4567S,158.0,4568.0,2017-05-01 20:00:00,04:00:00
153256,R238,R046,00-03-01,GRD CNTRL-42 ST,4567S,IRT,04/28/2017,20:00:00,REGULAR,17954683,7105882,4567S,GRD CNTRL-42 ST 4567S,0.0,4529.0,2017-04-28 20:00:00,04:00:00
153244,R238,R046,00-03-01,GRD CNTRL-42 ST,4567S,IRT,04/26/2017,20:00:00,REGULAR,17950185,7073815,4567S,GRD CNTRL-42 ST 4567S,625.0,4518.0,2017-04-26 20:00:00,04:00:00
151116,R238,R046,00-06-00,GRD CNTRL-42 ST,4567S,IRT,05/24/2017,12:00:00,REGULAR,1946426,2870930,4567S,GRD CNTRL-42 ST 4567S,0.0,4475.0,2017-05-24 12:00:00,04:00:00
152154,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,05/01/2017,12:00:00,REGULAR,13484780,5012955,4567S,GRD CNTRL-42 ST 4567S,718.0,4463.0,2017-05-01 12:00:00,04:00:00
153212,R238,R046,00-03-00,GRD CNTRL-42 ST,4567S,IRT,04/28/2017,12:00:00,REGULAR,13471900,4987675,4567S,GRD CNTRL-42 ST 4567S,818.0,4430.0,2017-04-28 12:00:00,04:00:00

In [29]:
new_df['HRSDIFF'] = new_df['TIMEDIFF'].apply(lambda row: int(row.seconds/3600) if not pd.isnull(row) else row)

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
new_df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF,HRSDIFF
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0,6.0,2017-05-20 04:00:00,04:00:00,4
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0,25.0,2017-05-20 08:00:00,04:00:00,4
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0,83.0,2017-05-20 12:00:00,04:00:00,4
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0,51.0,2017-05-20 16:00:00,04:00:00,4
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,20:00:00,REGULAR,6185506,2095379,456NQRW,59 ST 456NQRW,289.0,53.0,2017-05-20 20:00:00,04:00:00,4

In [31]:
new_df.HRSDIFF.value_counts()

4     944528
0       4478
1       2327
2       2203
3       1815
8       1136
12        33
16        19
20        15
5         13
6         11
7          9
10         6
17         5
15         4
14         4
13         3
11         3
22         2
19         2
21         2
18         1
23         1
Name: HRSDIFF, dtype: int64

In [32]:
new_df = new_df[new_df.HRSDIFF <= 4]

In [33]:
new_df.HRSDIFF.value_counts()

4    944528
0      4478
1      2327
2      2203
3      1815
Name: HRSDIFF, dtype: int64

In [34]:
def get_time_of_day(string):
    hour = int(string.split(":")[0])
    if hour <= 21 and hour > 17:
        tod = "Evening"
    elif hour <= 17 and hour > 13:
        tod = "Afternoon"
    elif hour <= 13 and hour > 9:
        tod = "Morning"
    elif hour <= 9 and hour > 5:
        tod = "Dawn"
    else:
        tod = 'Night'
    return tod
new_df["TIMEOFDAY"] = new_df["TIME"].apply(lambda row: get_time_of_day(row))

In [35]:
new_df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF,HRSDIFF,TIMEOFDAY
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0,6.0,2017-05-20 04:00:00,04:00:00,4,Night
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0,25.0,2017-05-20 08:00:00,04:00:00,4,Dawn
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0,83.0,2017-05-20 12:00:00,04:00:00,4,Morning
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0,51.0,2017-05-20 16:00:00,04:00:00,4,Afternoon
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,20:00:00,REGULAR,6185506,2095379,456NQRW,59 ST 456NQRW,289.0,53.0,2017-05-20 20:00:00,04:00:00,4,Evening

In [36]:
new_df['DAYWEEK'] = new_df['DATE']
new_df['DAYWEEK'] = pd.to_datetime(new_df['DAYWEEK'])
new_df['DAYWEEK'] = new_df['DAYWEEK'].dt.weekday_name

In [37]:
new_df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF,HRSDIFF,TIMEOFDAY,DAYWEEK
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,04:00:00,REGULAR,6184865,2095167,456NQRW,59 ST 456NQRW,24.0,6.0,2017-05-20 04:00:00,04:00:00,4,Night,Saturday
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,08:00:00,REGULAR,6184891,2095192,456NQRW,59 ST 456NQRW,26.0,25.0,2017-05-20 08:00:00,04:00:00,4,Dawn,Saturday
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,12:00:00,REGULAR,6184973,2095275,456NQRW,59 ST 456NQRW,82.0,83.0,2017-05-20 12:00:00,04:00:00,4,Morning,Saturday
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,16:00:00,REGULAR,6185217,2095326,456NQRW,59 ST 456NQRW,244.0,51.0,2017-05-20 16:00:00,04:00:00,4,Afternoon,Saturday
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/20/2017,20:00:00,REGULAR,6185506,2095379,456NQRW,59 ST 456NQRW,289.0,53.0,2017-05-20 20:00:00,04:00:00,4,Evening,Saturday

In [42]:
grouped_d = new_df.groupby(["STAT_MERGE", 'DATE',"DAYWEEK", "TIMEOFDAY"], as_index=False).agg({'ACTUALEXIT' : sum})
grouped_d.head()
len(grouped_d)

80753

In [43]:
grouped_means = grouped_d.groupby(["STAT_MERGE","DAYWEEK", "TIMEOFDAY"], as_index=False).ACTUALEXIT.mean()
grouped_means.head()
len(grouped_means)

16275

In [44]:
grouped_means.tail()

        STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
16270  ZEREGA AV 6  Wednesday  Afternoon       621.0
16271  ZEREGA AV 6  Wednesday       Dawn       482.8
16272  ZEREGA AV 6  Wednesday    Evening       842.0
16273  ZEREGA AV 6  Wednesday    Morning       324.2
16274  ZEREGA AV 6  Wednesday      Night       368.4

In [45]:
def top_five(new_df):
    days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    times = ['Dawn', 'Morning', 'Afternoon', 'Evening', 'Night']
    for day in days:
        for time in times:
            mask = ((new_df['DAYWEEK'] == day) & (new_df['TIMEOFDAY'] == time))
            temp_df = new_df[mask].sort_values(by = ['ACTUALEXIT'], ascending = False).reset_index()
            print(day, time,'\n', temp_df.head())

In [47]:
top_five(grouped_means)

Sunday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    926   14 ST-UNION SQ 456LNQRW  Sunday      Dawn      3133.6
1  10621     GRD CNTRL-42 ST 4567S  Sunday      Dawn      2853.4
2   3026  34 ST-HERALD SQ BDFMNQRW  Sunday      Dawn      2356.2
3   4636                 72 ST 123  Sunday      Dawn      2075.8
4   7926          CANAL ST 6JNQRWZ  Sunday      Dawn      1865.6
Sunday Morning
    index                   STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    928      14 ST-UNION SQ 456LNQRW  Sunday   Morning     12255.4
1   3028     34 ST-HERALD SQ BDFMNQRW  Sunday   Morning     10988.2
2  10623        GRD CNTRL-42 ST 4567S  Sunday   Morning      9331.4
3   7928             CANAL ST 6JNQRWZ  Sunday   Morning      8742.2
4  15313  TIMES SQ-42 ST 1237ACENQRSW  Sunday   Morning      8190.0
Sunday Afternoon
    index                   STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3025     34 ST-HERALD SQ BDFMNQRW  Sunday  Afternoon     16581.6
1    925      14 ST-UNION SQ 456LNQRW  Sunday  Afternoon     16447.2
2  15310  TIMES SQ-42 ST 1237ACENQRSW  Sunday  Afternoon     15663.6
3  10620        GRD CNTRL-42 ST 4567S  Sunday  Afternoon     11981.2
4   4145         59 ST COLUMBUS 1ABCD  Sunday  Afternoon     10541.6
Sunday Evening
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3027      34 ST-HERALD SQ BDFMNQRW  Sunday   Evening     14692.0
1  15312   TIMES SQ-42 ST 1237ACENQRSW  Sunday   Evening     13188.0
2    927       14 ST-UNION SQ 456LNQRW  Sunday   Evening     11071.8
3   3482  42 ST-PORT AUTH 1237ACENQRSW  Sunday   Evening     10689.6
4  10622         GRD CNTRL-42 ST 4567S  Sunday   Evening     10493.8
Sunday Night
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3029      34 ST-HERALD SQ BDFMNQRW  Sunday     Night     10316.6
1  15314   TIMES SQ-42 ST 1237ACENQRSW  Sunday     Night     10285.2
2   3484  42 ST-PORT AUTH 1237ACENQRSW  Sunday     Night      9797.8
3  11569         JKSN HT-ROOSVLT 7EFMR  Sunday     Night      9163.6
4   9854               FLUSHING-MAIN 7  Sunday     Night      7755.4
Monday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10611     GRD CNTRL-42 ST 4567S  Monday      Dawn     32725.0
1    916   14 ST-UNION SQ 456LNQRW  Monday      Dawn     18857.2
2  10296        FULTON ST 2345ACJZ  Monday      Dawn     16119.4
3  13796            PATH NEW WTC 1  Monday      Dawn     14216.8
4   3016  34 ST-HERALD SQ BDFMNQRW  Monday      Dawn     11334.8
Monday Morning
    index                   STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10613        GRD CNTRL-42 ST 4567S  Monday   Morning     41065.6
1   3018     34 ST-HERALD SQ BDFMNQRW  Monday   Morning     36773.2
2   3613          47-50 STS ROCK BDFM  Monday   Morning     35787.0
3  15303  TIMES SQ-42 ST 1237ACENQRSW  Monday   Morning     30686.0
4  10298           FULTON ST 2345ACJZ  Monday   Morning     29509.4
Monday Afternoon
    index                   STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0  10610        GRD CNTRL-42 ST 4567S  Monday  Afternoon     24105.0
1   3015     34 ST-HERALD SQ BDFMNQRW  Monday  Afternoon     20871.8
2    915      14 ST-UNION SQ 456LNQRW  Monday  Afternoon     19819.6
3  15300  TIMES SQ-42 ST 1237ACENQRSW  Monday  Afternoon     14514.8
4  10295           FULTON ST 2345ACJZ  Monday  Afternoon     13152.2
Monday Evening
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10612         GRD CNTRL-42 ST 4567S  Monday   Evening     30662.2
1   3017      34 ST-HERALD SQ BDFMNQRW  Monday   Evening     30526.4
2   3472  42 ST-PORT AUTH 1237ACENQRSW  Monday   Evening     27189.2
3   3157            34 ST-PENN STA ACE  Monday   Evening     26324.8
4    917       14 ST-UNION SQ 456LNQRW  Monday   Evening     19898.6
Monday Night
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3124         34 ST-PENN STA 123ACE  Monday     Night      9583.8
1  11664                KEW GARDENS EF  Monday     Night      8994.4
2   3474  42 ST-PORT AUTH 1237ACENQRSW  Monday     Night      7892.6
3  11594              JOURNAL SQUARE 1  Monday     Night      7553.4
4  11559         JKSN HT-ROOSVLT 7EFMR  Monday     Night      7062.4
Tuesday Dawn
    index                STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10631     GRD CNTRL-42 ST 4567S  Tuesday      Dawn     34577.4
1    936   14 ST-UNION SQ 456LNQRW  Tuesday      Dawn     19611.0
2  10316        FULTON ST 2345ACJZ  Tuesday      Dawn     16686.4
3  13816            PATH NEW WTC 1  Tuesday      Dawn     14832.8
4   3036  34 ST-HERALD SQ BDFMNQRW  Tuesday      Dawn     10989.0
Tuesday Morning
    index                   STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10633        GRD CNTRL-42 ST 4567S  Tuesday   Morning     44033.0
1   3038     34 ST-HERALD SQ BDFMNQRW  Tuesday   Morning     37477.0
2   3633          47-50 STS ROCK BDFM  Tuesday   Morning     36391.2
3  15323  TIMES SQ-42 ST 1237ACENQRSW  Tuesday   Morning     32367.6
4  10318           FULTON ST 2345ACJZ  Tuesday   Morning     30071.2
Tuesday Afternoon
    index                   STAT_MERGE  DAYWEEK  TIMEOFDAY  ACTUALEXIT
0  10630        GRD CNTRL-42 ST 4567S  Tuesday  Afternoon     23272.4
1   3035     34 ST-HERALD SQ BDFMNQRW  Tuesday  Afternoon     20812.4
2    935      14 ST-UNION SQ 456LNQRW  Tuesday  Afternoon     20002.2
3  15320  TIMES SQ-42 ST 1237ACENQRSW  Tuesday  Afternoon     15466.0
4  10315           FULTON ST 2345ACJZ  Tuesday  Afternoon     13560.8
Tuesday Evening
    index                    STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3037      34 ST-HERALD SQ BDFMNQRW  Tuesday   Evening     32880.6
1  10632         GRD CNTRL-42 ST 4567S  Tuesday   Evening     30733.2
2   3492  42 ST-PORT AUTH 1237ACENQRSW  Tuesday   Evening     27535.4
3   3177            34 ST-PENN STA ACE  Tuesday   Evening     27300.2
4    937       14 ST-UNION SQ 456LNQRW  Tuesday   Evening     21404.8
Tuesday Night
    index                    STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3144         34 ST-PENN STA 123ACE  Tuesday     Night     10811.4
1   3494  42 ST-PORT AUTH 1237ACENQRSW  Tuesday     Night     10574.8
2  11684                KEW GARDENS EF  Tuesday     Night      9958.4
3  11579         JKSN HT-ROOSVLT 7EFMR  Tuesday     Night      9467.2
4   9864               FLUSHING-MAIN 7  Tuesday     Night      9316.4
Wednesday Dawn
    index                STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10636     GRD CNTRL-42 ST 4567S  Wednesday      Dawn     32778.0
1    941   14 ST-UNION SQ 456LNQRW  Wednesday      Dawn     20026.4
2  10321        FULTON ST 2345ACJZ  Wednesday      Dawn     17401.8
3  13821            PATH NEW WTC 1  Wednesday      Dawn     14277.6
4   3041  34 ST-HERALD SQ BDFMNQRW  Wednesday      Dawn     10789.4
Wednesday Morning
    index                   STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10638        GRD CNTRL-42 ST 4567S  Wednesday   Morning     44831.6
1   3043     34 ST-HERALD SQ BDFMNQRW  Wednesday   Morning     39865.2
2   3638          47-50 STS ROCK BDFM  Wednesday   Morning     36717.6
3  15328  TIMES SQ-42 ST 1237ACENQRSW  Wednesday   Morning     33157.2
4  10323           FULTON ST 2345ACJZ  Wednesday   Morning     29535.4
Wednesday Afternoon
    index                   STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
0  10635        GRD CNTRL-42 ST 4567S  Wednesday  Afternoon     25444.2
1   3040     34 ST-HERALD SQ BDFMNQRW  Wednesday  Afternoon     23392.4
2    940      14 ST-UNION SQ 456LNQRW  Wednesday  Afternoon     21127.0
3  15325  TIMES SQ-42 ST 1237ACENQRSW  Wednesday  Afternoon     17760.8
4  10320           FULTON ST 2345ACJZ  Wednesday  Afternoon     13620.8
Wednesday Evening
    index                    STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3042      34 ST-HERALD SQ BDFMNQRW  Wednesday   Evening     32807.6
1  10637         GRD CNTRL-42 ST 4567S  Wednesday   Evening     30930.0
2   3497  42 ST-PORT AUTH 1237ACENQRSW  Wednesday   Evening     26754.2
3   3182            34 ST-PENN STA ACE  Wednesday   Evening     25889.8
4    942       14 ST-UNION SQ 456LNQRW  Wednesday   Evening     22304.0
Wednesday Night
    index                    STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3499  42 ST-PORT AUTH 1237ACENQRSW  Wednesday     Night     11573.4
1   3149         34 ST-PENN STA 123ACE  Wednesday     Night     10512.4
2  11689                KEW GARDENS EF  Wednesday     Night     10503.6
3   9869               FLUSHING-MAIN 7  Wednesday     Night      9860.4
4  11584         JKSN HT-ROOSVLT 7EFMR  Wednesday     Night      9725.4
Thursday Dawn
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10626     GRD CNTRL-42 ST 4567S  Thursday      Dawn     31066.2
1    931   14 ST-UNION SQ 456LNQRW  Thursday      Dawn     19391.6
2  10311        FULTON ST 2345ACJZ  Thursday      Dawn     16098.2
3  13811            PATH NEW WTC 1  Thursday      Dawn     14789.0
4   3031  34 ST-HERALD SQ BDFMNQRW  Thursday      Dawn     10586.2
Thursday Morning
    index                   STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10628        GRD CNTRL-42 ST 4567S  Thursday   Morning     41347.6
1   3033     34 ST-HERALD SQ BDFMNQRW  Thursday   Morning     39724.6
2   3628          47-50 STS ROCK BDFM  Thursday   Morning     37089.0
3  15318  TIMES SQ-42 ST 1237ACENQRSW  Thursday   Morning     32136.6
4  10313           FULTON ST 2345ACJZ  Thursday   Morning     29627.2
Thursday Afternoon
    index                   STAT_MERGE   DAYWEEK  TIMEOFDAY  ACTUALEXIT
0  10625        GRD CNTRL-42 ST 4567S  Thursday  Afternoon     26679.2
1   3030     34 ST-HERALD SQ BDFMNQRW  Thursday  Afternoon     23971.4
2    930      14 ST-UNION SQ 456LNQRW  Thursday  Afternoon     21037.8
3  15315  TIMES SQ-42 ST 1237ACENQRSW  Thursday  Afternoon     16442.2
4   3170           34 ST-PENN STA ACE  Thursday  Afternoon     14477.8
Thursday Evening
    index                    STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3032      34 ST-HERALD SQ BDFMNQRW  Thursday   Evening    34116.20
1  10627         GRD CNTRL-42 ST 4567S  Thursday   Evening    32705.80
2   3172            34 ST-PENN STA ACE  Thursday   Evening    28142.00
3   3487  42 ST-PORT AUTH 1237ACENQRSW  Thursday   Evening    27668.20
4    932       14 ST-UNION SQ 456LNQRW  Thursday   Evening    22757.75
Thursday Night
    index                    STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3489  42 ST-PORT AUTH 1237ACENQRSW  Thursday     Night     11750.0
1   3139         34 ST-PENN STA 123ACE  Thursday     Night     11300.4
2  11574         JKSN HT-ROOSVLT 7EFMR  Thursday     Night     10266.2
3   9859               FLUSHING-MAIN 7  Thursday     Night      9965.8
4  11679                KEW GARDENS EF  Thursday     Night      9963.6
Friday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10606     GRD CNTRL-42 ST 4567S  Friday      Dawn     29049.2
1    911   14 ST-UNION SQ 456LNQRW  Friday      Dawn     17895.4
2  10291        FULTON ST 2345ACJZ  Friday      Dawn     13843.6
3  13791            PATH NEW WTC 1  Friday      Dawn     11186.2
4   3011  34 ST-HERALD SQ BDFMNQRW  Friday      Dawn     10174.6
Friday Morning
    index                   STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  10608        GRD CNTRL-42 ST 4567S  Friday   Morning     41791.2
1   3013     34 ST-HERALD SQ BDFMNQRW  Friday   Morning     37422.6
2   3608          47-50 STS ROCK BDFM  Friday   Morning     33706.8
3  15298  TIMES SQ-42 ST 1237ACENQRSW  Friday   Morning     29531.4
4  10293           FULTON ST 2345ACJZ  Friday   Morning     27431.4
Friday Afternoon
    index                   STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0  10605        GRD CNTRL-42 ST 4567S  Friday  Afternoon     27983.8
1   3010     34 ST-HERALD SQ BDFMNQRW  Friday  Afternoon     25663.6
2    910      14 ST-UNION SQ 456LNQRW  Friday  Afternoon     21734.6
3  15295  TIMES SQ-42 ST 1237ACENQRSW  Friday  Afternoon     17109.0
4   3150           34 ST-PENN STA ACE  Friday  Afternoon     16990.4
Friday Evening
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3012      34 ST-HERALD SQ BDFMNQRW  Friday   Evening     32644.0
1  10607         GRD CNTRL-42 ST 4567S  Friday   Evening     28591.2
2   3467  42 ST-PORT AUTH 1237ACENQRSW  Friday   Evening     24908.6
3   3152            34 ST-PENN STA ACE  Friday   Evening     24396.4
4  15297   TIMES SQ-42 ST 1237ACENQRSW  Friday   Evening     22480.2
Friday Night
    index                    STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3469  42 ST-PORT AUTH 1237ACENQRSW  Friday     Night    12827.20
1  11554         JKSN HT-ROOSVLT 7EFMR  Friday     Night    10675.75
2   3014      34 ST-HERALD SQ BDFMNQRW  Friday     Night    10216.20
3   3119         34 ST-PENN STA 123ACE  Friday     Night     9029.60
4   9839               FLUSHING-MAIN 7  Friday     Night     8796.20
Saturday Dawn
    index                   STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0    921      14 ST-UNION SQ 456LNQRW  Saturday      Dawn      5131.6
1  10616        GRD CNTRL-42 ST 4567S  Saturday      Dawn      5021.2
2   3021     34 ST-HERALD SQ BDFMNQRW  Saturday      Dawn      3707.6
3   4631                    72 ST 123  Saturday      Dawn      2865.6
4  15306  TIMES SQ-42 ST 1237ACENQRSW  Saturday      Dawn      2725.8
Saturday Morning
    index                   STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0    923      14 ST-UNION SQ 456LNQRW  Saturday   Morning     16910.0
1   3023     34 ST-HERALD SQ BDFMNQRW  Saturday   Morning     14629.8
2  10618        GRD CNTRL-42 ST 4567S  Saturday   Morning     12303.2
3  15308  TIMES SQ-42 ST 1237ACENQRSW  Saturday   Morning     11049.6
4   4143         59 ST COLUMBUS 1ABCD  Saturday   Morning     10319.0
Saturday Afternoon
    index                   STAT_MERGE   DAYWEEK  TIMEOFDAY  ACTUALEXIT
0    920      14 ST-UNION SQ 456LNQRW  Saturday  Afternoon     20221.2
1   3020     34 ST-HERALD SQ BDFMNQRW  Saturday  Afternoon     20032.8
2  15305  TIMES SQ-42 ST 1237ACENQRSW  Saturday  Afternoon     17716.4
3  10615        GRD CNTRL-42 ST 4567S  Saturday  Afternoon     15331.8
4   4140         59 ST COLUMBUS 1ABCD  Saturday  Afternoon     11279.2
Saturday Evening
    index                    STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0  15307   TIMES SQ-42 ST 1237ACENQRSW  Saturday   Evening     18486.2
1   3022      34 ST-HERALD SQ BDFMNQRW  Saturday   Evening     18260.8
2    922       14 ST-UNION SQ 456LNQRW  Saturday   Evening     15050.0
3  10617         GRD CNTRL-42 ST 4567S  Saturday   Evening     13037.8
4   3477  42 ST-PORT AUTH 1237ACENQRSW  Saturday   Evening     12859.4
Saturday Night
    index                    STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3479  42 ST-PORT AUTH 1237ACENQRSW  Saturday     Night      4329.2
1   3129         34 ST-PENN STA 123ACE  Saturday     Night      4304.2
2  11669                KEW GARDENS EF  Saturday     Night      3484.2
3  11564         JKSN HT-ROOSVLT 7EFMR  Saturday     Night      2986.2
4   3444  42 ST-PORT AUTH 1237ACEGNRSW  Saturday     Night      2727.0

In [97]:
(grouped_means
 .sort_values(by=['DAYWEEK','TIMEOFDAY', 'ACTUALEXIT'], ascending=[True,True,False])
 .groupby(['DAYWEEK','TIMEOFDAY'])
 .head())

                         STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
10605         GRD CNTRL-42 ST 4567S     Friday  Afternoon    27983.80
3010       34 ST-HERALD SQ BDFMNQRW     Friday  Afternoon    25663.60
910         14 ST-UNION SQ 456LNQRW     Friday  Afternoon    21734.60
15295   TIMES SQ-42 ST 1237ACENQRSW     Friday  Afternoon    17109.00
3150             34 ST-PENN STA ACE     Friday  Afternoon    16990.40
10606         GRD CNTRL-42 ST 4567S     Friday       Dawn    29049.20
911         14 ST-UNION SQ 456LNQRW     Friday       Dawn    17895.40
10291            FULTON ST 2345ACJZ     Friday       Dawn    13843.60
13791                PATH NEW WTC 1     Friday       Dawn    11186.20
3011       34 ST-HERALD SQ BDFMNQRW     Friday       Dawn    10174.60
3012       34 ST-HERALD SQ BDFMNQRW     Friday    Evening    32644.00
10607         GRD CNTRL-42 ST 4567S     Friday    Evening    28591.20
3467   42 ST-PORT AUTH 1237ACENQRSW     Friday    Evening    24908.60
3152             34 ST-PENN STA ACE     Friday    Evening    24396.40
15297   TIMES SQ-42 ST 1237ACENQRSW     Friday    Evening    22480.20
10608         GRD CNTRL-42 ST 4567S     Friday    Morning    41791.20
3013       34 ST-HERALD SQ BDFMNQRW     Friday    Morning    37422.60
3608            47-50 STS ROCK BDFM     Friday    Morning    33706.80
15298   TIMES SQ-42 ST 1237ACENQRSW     Friday    Morning    29531.40
10293            FULTON ST 2345ACJZ     Friday    Morning    27431.40
3469   42 ST-PORT AUTH 1237ACENQRSW     Friday      Night    12827.20
11554         JKSN HT-ROOSVLT 7EFMR     Friday      Night    10675.75
3014       34 ST-HERALD SQ BDFMNQRW     Friday      Night    10216.20
3119          34 ST-PENN STA 123ACE     Friday      Night     9029.60
9839                FLUSHING-MAIN 7     Friday      Night     8796.20
10610         GRD CNTRL-42 ST 4567S     Monday  Afternoon    24105.00
3015       34 ST-HERALD SQ BDFMNQRW     Monday  Afternoon    20871.80
915         14 ST-UNION SQ 456LNQRW     Monday  Afternoon    19819.60
15300   TIMES SQ-42 ST 1237ACENQRSW     Monday  Afternoon    14514.80
10295            FULTON ST 2345ACJZ     Monday  Afternoon    13152.20
10611         GRD CNTRL-42 ST 4567S     Monday       Dawn    32725.00
916         14 ST-UNION SQ 456LNQRW     Monday       Dawn    18857.20
10296            FULTON ST 2345ACJZ     Monday       Dawn    16119.40
13796                PATH NEW WTC 1     Monday       Dawn    14216.80
3016       34 ST-HERALD SQ BDFMNQRW     Monday       Dawn    11334.80
10612         GRD CNTRL-42 ST 4567S     Monday    Evening    30662.20
3017       34 ST-HERALD SQ BDFMNQRW     Monday    Evening    30526.40
3472   42 ST-PORT AUTH 1237ACENQRSW     Monday    Evening    27189.20
3157             34 ST-PENN STA ACE     Monday    Evening    26324.80
917         14 ST-UNION SQ 456LNQRW     Monday    Evening    19898.60
10613         GRD CNTRL-42 ST 4567S     Monday    Morning    41065.60
3018       34 ST-HERALD SQ BDFMNQRW     Monday    Morning    36773.20
3613            47-50 STS ROCK BDFM     Monday    Morning    35787.00
15303   TIMES SQ-42 ST 1237ACENQRSW     Monday    Morning    30686.00
10298            FULTON ST 2345ACJZ     Monday    Morning    29509.40
3124          34 ST-PENN STA 123ACE     Monday      Night     9583.80
11664                KEW GARDENS EF     Monday      Night     8994.40
3474   42 ST-PORT AUTH 1237ACENQRSW     Monday      Night     7892.60
11594              JOURNAL SQUARE 1     Monday      Night     7553.40
11559         JKSN HT-ROOSVLT 7EFMR     Monday      Night     7062.40
920         14 ST-UNION SQ 456LNQRW   Saturday  Afternoon    20221.20
3020       34 ST-HERALD SQ BDFMNQRW   Saturday  Afternoon    20032.80
15305   TIMES SQ-42 ST 1237ACENQRSW   Saturday  Afternoon    17716.40
10615         GRD CNTRL-42 ST 4567S   Saturday  Afternoon    15331.80
4140           59 ST COLUMBUS 1ABCD   Saturday  Afternoon    11279.20
921         14 ST-UNION SQ 456LNQRW   Saturday       Dawn     5131.60
10616         GRD CNTRL-42 ST 4567S   Saturday       Dawn     5021.20
3021       34 ST-HERALD SQ BDFMNQRW   Saturday       Dawn     3707.60
4631                      72 ST 123   Saturday       Dawn     2865.60
15306   TIMES SQ-42 ST 1237ACENQRSW   Saturday       Dawn     2725.80
15307   TIMES SQ-42 ST 1237ACENQRSW   Saturday    Evening    18486.20
3022       34 ST-HERALD SQ BDFMNQRW   Saturday    Evening    18260.80
922         14 ST-UNION SQ 456LNQRW   Saturday    Evening    15050.00
10617         GRD CNTRL-42 ST 4567S   Saturday    Evening    13037.80
3477   42 ST-PORT AUTH 1237ACENQRSW   Saturday    Evening    12859.40
923         14 ST-UNION SQ 456LNQRW   Saturday    Morning    16910.00
3023       34 ST-HERALD SQ BDFMNQRW   Saturday    Morning    14629.80
10618         GRD CNTRL-42 ST 4567S   Saturday    Morning    12303.20
15308   TIMES SQ-42 ST 1237ACENQRSW   Saturday    Morning    11049.60
4143           59 ST COLUMBUS 1ABCD   Saturday    Morning    10319.00
3479   42 ST-PORT AUTH 1237ACENQRSW   Saturday      Night     4329.20
3129          34 ST-PENN STA 123ACE   Saturday      Night     4304.20
11669                KEW GARDENS EF   Saturday      Night     3484.20
11564         JKSN HT-ROOSVLT 7EFMR   Saturday      Night     2986.20
3444   42 ST-PORT AUTH 1237ACEGNRSW   Saturday      Night     2727.00
3025       34 ST-HERALD SQ BDFMNQRW     Sunday  Afternoon    16581.60
925         14 ST-UNION SQ 456LNQRW     Sunday  Afternoon    16447.20
15310   TIMES SQ-42 ST 1237ACENQRSW     Sunday  Afternoon    15663.60
10620         GRD CNTRL-42 ST 4567S     Sunday  Afternoon    11981.20
4145           59 ST COLUMBUS 1ABCD     Sunday  Afternoon    10541.60
926         14 ST-UNION SQ 456LNQRW     Sunday       Dawn     3133.60
10621         GRD CNTRL-42 ST 4567S     Sunday       Dawn     2853.40
3026       34 ST-HERALD SQ BDFMNQRW     Sunday       Dawn     2356.20
4636                      72 ST 123     Sunday       Dawn     2075.80
7926               CANAL ST 6JNQRWZ     Sunday       Dawn     1865.60
3027       34 ST-HERALD SQ BDFMNQRW     Sunday    Evening    14692.00
15312   TIMES SQ-42 ST 1237ACENQRSW     Sunday    Evening    13188.00
927         14 ST-UNION SQ 456LNQRW     Sunday    Evening    11071.80
3482   42 ST-PORT AUTH 1237ACENQRSW     Sunday    Evening    10689.60
10622         GRD CNTRL-42 ST 4567S     Sunday    Evening    10493.80
928         14 ST-UNION SQ 456LNQRW     Sunday    Morning    12255.40
3028       34 ST-HERALD SQ BDFMNQRW     Sunday    Morning    10988.20
10623         GRD CNTRL-42 ST 4567S     Sunday    Morning     9331.40
7928               CANAL ST 6JNQRWZ     Sunday    Morning     8742.20
15313   TIMES SQ-42 ST 1237ACENQRSW     Sunday    Morning     8190.00
3029       34 ST-HERALD SQ BDFMNQRW     Sunday      Night    10316.60
15314   TIMES SQ-42 ST 1237ACENQRSW     Sunday      Night    10285.20
3484   42 ST-PORT AUTH 1237ACENQRSW     Sunday      Night     9797.80
11569         JKSN HT-ROOSVLT 7EFMR     Sunday      Night     9163.60
9854                FLUSHING-MAIN 7     Sunday      Night     7755.40
10625         GRD CNTRL-42 ST 4567S   Thursday  Afternoon    26679.20
3030       34 ST-HERALD SQ BDFMNQRW   Thursday  Afternoon    23971.40
930         14 ST-UNION SQ 456LNQRW   Thursday  Afternoon    21037.80
15315   TIMES SQ-42 ST 1237ACENQRSW   Thursday  Afternoon    16442.20
3170             34 ST-PENN STA ACE   Thursday  Afternoon    14477.80
10626         GRD CNTRL-42 ST 4567S   Thursday       Dawn    31066.20
931         14 ST-UNION SQ 456LNQRW   Thursday       Dawn    19391.60
10311            FULTON ST 2345ACJZ   Thursday       Dawn    16098.20
13811                PATH NEW WTC 1   Thursday       Dawn    14789.00
3031       34 ST-HERALD SQ BDFMNQRW   Thursday       Dawn    10586.20
3032       34 ST-HERALD SQ BDFMNQRW   Thursday    Evening    34116.20
10627         GRD CNTRL-42 ST 4567S   Thursday    Evening    32705.80
3172             34 ST-PENN STA ACE   Thursday    Evening    28142.00
3487   42 ST-PORT AUTH 1237ACENQRSW   Thursday    Evening    27668.20
932         14 ST-UNION SQ 456LNQRW   Thursday    Evening    22757.75
10628         GRD CNTRL-42 ST 4567S   Thursday    Morning    41347.60
3033       34 ST-HERALD SQ BDFMNQRW   Thursday    Morning    39724.60
3628            47-50 STS ROCK BDFM   Thursday    Morning    37089.00
15318   TIMES SQ-42 ST 1237ACENQRSW   Thursday    Morning    32136.60
10313            FULTON ST 2345ACJZ   Thursday    Morning    29627.20
3489   42 ST-PORT AUTH 1237ACENQRSW   Thursday      Night    11750.00
3139          34 ST-PENN STA 123ACE   Thursday      Night    11300.40
11574         JKSN HT-ROOSVLT 7EFMR   Thursday      Night    10266.20
9859                FLUSHING-MAIN 7   Thursday      Night     9965.80
11679                KEW GARDENS EF   Thursday      Night     9963.60
10630         GRD CNTRL-42 ST 4567S    Tuesday  Afternoon    23272.40
3035       34 ST-HERALD SQ BDFMNQRW    Tuesday  Afternoon    20812.40
935         14 ST-UNION SQ 456LNQRW    Tuesday  Afternoon    20002.20
15320   TIMES SQ-42 ST 1237ACENQRSW    Tuesday  Afternoon    15466.00
10315            FULTON ST 2345ACJZ    Tuesday  Afternoon    13560.80
10631         GRD CNTRL-42 ST 4567S    Tuesday       Dawn    34577.40
936         14 ST-UNION SQ 456LNQRW    Tuesday       Dawn    19611.00
10316            FULTON ST 2345ACJZ    Tuesday       Dawn    16686.40
13816                PATH NEW WTC 1    Tuesday       Dawn    14832.80
3036       34 ST-HERALD SQ BDFMNQRW    Tuesday       Dawn    10989.00
3037       34 ST-HERALD SQ BDFMNQRW    Tuesday    Evening    32880.60
10632         GRD CNTRL-42 ST 4567S    Tuesday    Evening    30733.20
3492   42 ST-PORT AUTH 1237ACENQRSW    Tuesday    Evening    27535.40
3177             34 ST-PENN STA ACE    Tuesday    Evening    27300.20
937         14 ST-UNION SQ 456LNQRW    Tuesday    Evening    21404.80
10633         GRD CNTRL-42 ST 4567S    Tuesday    Morning    44033.00
3038       34 ST-HERALD SQ BDFMNQRW    Tuesday    Morning    37477.00
3633            47-50 STS ROCK BDFM    Tuesday    Morning    36391.20
15323   TIMES SQ-42 ST 1237ACENQRSW    Tuesday    Morning    32367.60
10318            FULTON ST 2345ACJZ    Tuesday    Morning    30071.20
3144          34 ST-PENN STA 123ACE    Tuesday      Night    10811.40
3494   42 ST-PORT AUTH 1237ACENQRSW    Tuesday      Night    10574.80
11684                KEW GARDENS EF    Tuesday      Night     9958.40
11579         JKSN HT-ROOSVLT 7EFMR    Tuesday      Night     9467.20
9864                FLUSHING-MAIN 7    Tuesday      Night     9316.40
10635         GRD CNTRL-42 ST 4567S  Wednesday  Afternoon    25444.20
3040       34 ST-HERALD SQ BDFMNQRW  Wednesday  Afternoon    23392.40
940         14 ST-UNION SQ 456LNQRW  Wednesday  Afternoon    21127.00
15325   TIMES SQ-42 ST 1237ACENQRSW  Wednesday  Afternoon    17760.80
10320            FULTON ST 2345ACJZ  Wednesday  Afternoon    13620.80
10636         GRD CNTRL-42 ST 4567S  Wednesday       Dawn    32778.00
941         14 ST-UNION SQ 456LNQRW  Wednesday       Dawn    20026.40
10321            FULTON ST 2345ACJZ  Wednesday       Dawn    17401.80
13821                PATH NEW WTC 1  Wednesday       Dawn    14277.60
3041       34 ST-HERALD SQ BDFMNQRW  Wednesday       Dawn    10789.40
3042       34 ST-HERALD SQ BDFMNQRW  Wednesday    Evening    32807.60
10637         GRD CNTRL-42 ST 4567S  Wednesday    Evening    30930.00
3497   42 ST-PORT AUTH 1237ACENQRSW  Wednesday    Evening    26754.20
3182             34 ST-PENN STA ACE  Wednesday    Evening    25889.80
942         14 ST-UNION SQ 456LNQRW  Wednesday    Evening    22304.00
10638         GRD CNTRL-42 ST 4567S  Wednesday    Morning    44831.60
3043       34 ST-HERALD SQ BDFMNQRW  Wednesday    Morning    39865.20
3638            47-50 STS ROCK BDFM  Wednesday    Morning    36717.60
15328   TIMES SQ-42 ST 1237ACENQRSW  Wednesday    Morning    33157.20
10323            FULTON ST 2345ACJZ  Wednesday    Morning    29535.40
3499   42 ST-PORT AUTH 1237ACENQRSW  Wednesday      Night    11573.40
3149          34 ST-PENN STA 123ACE  Wednesday      Night    10512.40
11689                KEW GARDENS EF  Wednesday      Night    10503.60
9869                FLUSHING-MAIN 7  Wednesday      Night     9860.40
11584         JKSN HT-ROOSVLT 7EFMR  Wednesday      Night     9725.40

In [87]:
no_hubs = new_df.drop(new_df[(new_df.STAT_MERGE == 'GRD CNTRL-42 ST 4567S') | 
                            (new_df.STAT_MERGE == 'TIMES SQ-42 ST 1237ACENQRSW') | 
                            (new_df.STAT_MERGE == '42 ST-PORT AUTH 1237ACENQRSW') |
                            (new_df.STAT_MERGE == '34 ST-PENN STA ACE') |
                            (new_df.STAT_MERGE == '34 ST-PENN STA 123ACE') |
                            (new_df.STAT_MERGE == '42 ST-PORT AUTH 1237ACEGNRSW')
                            ].index)

In [88]:
no_hubs.sample(10)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,LINESORT,STAT_MERGE,ACTUALENTRY,ACTUALEXIT,DATE_TIME,TIMEDIFF,HRSDIFF,TIMEOFDAY,DAYWEEK
174168,R507,R134,00-03-00,HUNTERS PT AV,7,IRT,05/19/2017,17:00:00,REGULAR,1375630,4092832,7,HUNTERS PT AV 7,55.0,218.0,2017-05-19 17:00:00,04:00:00,4,Afternoon,Friday
79139,N325A,R218,00-05-00,ELMHURST AV,MR,IND,05/23/2017,20:00:00,REGULAR,5142616,843502,MR,ELMHURST AV MR,64.0,76.0,2017-05-23 20:00:00,04:00:00,4,Evening,Tuesday
88567,N405,R239,00-06-01,GREENPOINT AV,G,IND,04/30/2017,04:00:00,REGULAR,2787436,28803,G,GREENPOINT AV G,44.0,0.0,2017-04-30 04:00:00,04:00:00,4,Night,Sunday
142080,R201,R041,00-05-01,BOWLING GREEN,45,IRT,05/15/2017,20:00:00,REGULAR,117440516,318,45,BOWLING GREEN 45,0.0,0.0,2017-05-15 20:00:00,04:00:00,4,Evening,Monday
93845,N505,R022,02-00-06,34 ST-HERALD SQ,BDFMNQRW,IND,05/01/2017,16:00:00,REGULAR,3520477,4265887,BDFMNQRW,34 ST-HERALD SQ BDFMNQRW,136.0,129.0,2017-05-01 16:00:00,04:00:00,4,Afternoon,Monday
165183,R321,R386,01-00-01,174 ST,25,IRT,05/26/2017,17:00:00,REGULAR,908724,2016556,25,174 ST 25,192.0,323.0,2017-05-26 17:00:00,04:00:00,4,Afternoon,Friday
20180,C009,R057,03-00-00,ATL AV-BARCLAY,BDNQR2345,BMT,05/25/2017,12:00:00,REGULAR,568785,1102223,2345BDNQR,ATL AV-BARCLAY 2345BDNQR,332.0,539.0,2017-05-25 12:00:00,04:00:00,4,Morning,Thursday
171881,R419,R326,00-03-01,ZEREGA AV,6,IRT,05/15/2017,01:00:00,REGULAR,65958,11997,6,ZEREGA AV 6,35.0,22.0,2017-05-15 01:00:00,04:00:00,4,Night,Monday
67791,N186,R418,00-05-01,BEACH 105 ST,AS,IND,04/26/2017,10:06:32,REGULAR,117440512,25,AS,BEACH 105 ST AS,0.0,0.0,2017-04-26 10:06:32,01:06:32,1,Morning,Wednesday
96372,N513,R163,04-00-01,14 ST,FLM123,IND,05/04/2017,12:00:00,REGULAR,884491,725651,123FLM,14 ST 123FLM,349.0,435.0,2017-05-04 12:00:00,04:00:00,4,Morning,Thursday

In [89]:
grouped_nohubs = no_hubs.groupby(["STAT_MERGE", 'DATE',"DAYWEEK", "TIMEOFDAY"], as_index=False).agg({'ACTUALEXIT' : sum})
len(grouped_nohubs)

78837

In [90]:
grouped_means_nohubs = grouped_nohubs.groupby(["STAT_MERGE","DAYWEEK", "TIMEOFDAY"], as_index=False).ACTUALEXIT.mean()
len(grouped_means_nohubs)

16065

In [91]:
grouped_means_nohubs.tail()

        STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
16060  ZEREGA AV 6  Wednesday  Afternoon       621.0
16061  ZEREGA AV 6  Wednesday       Dawn       482.8
16062  ZEREGA AV 6  Wednesday    Evening       842.0
16063  ZEREGA AV 6  Wednesday    Morning       324.2
16064  ZEREGA AV 6  Wednesday      Night       368.4

In [92]:
top_five(grouped_means_nohubs)

Sunday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    926   14 ST-UNION SQ 456LNQRW  Sunday      Dawn      3133.6
1   3026  34 ST-HERALD SQ BDFMNQRW  Sunday      Dawn      2340.6
2   4496                 72 ST 123  Sunday      Dawn      2049.0
3   7786          CANAL ST 6JNQRWZ  Sunday      Dawn      1865.6
4   5406                 96 ST 123  Sunday      Dawn      1785.4
Sunday Morning
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    928   14 ST-UNION SQ 456LNQRW  Sunday   Morning     12255.4
1   3028  34 ST-HERALD SQ BDFMNQRW  Sunday   Morning     10862.0
2   7788          CANAL ST 6JNQRWZ  Sunday   Morning      8742.2
3   4498                 72 ST 123  Sunday   Morning      7111.8
4  15488    W 4 ST-WASH SQ ABCDEFM  Sunday   Morning      6663.6
Sunday Afternoon
    index                STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0    925   14 ST-UNION SQ 456LNQRW  Sunday  Afternoon     16447.2
1   3025  34 ST-HERALD SQ BDFMNQRW  Sunday  Afternoon     16321.4
2   4005      59 ST COLUMBUS 1ABCD  Sunday  Afternoon      9108.0
3   4495                 72 ST 123  Sunday  Afternoon      9036.8
4   7785          CANAL ST 6JNQRWZ  Sunday  Afternoon      8116.8
Sunday Evening
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3027  34 ST-HERALD SQ BDFMNQRW  Sunday   Evening     14437.0
1    927   14 ST-UNION SQ 456LNQRW  Sunday   Evening     11071.8
2  11392     JKSN HT-ROOSVLT 7EFMR  Sunday   Evening      7962.6
3   9712           FLUSHING-MAIN 7  Sunday   Evening      7651.0
4   5407                 96 ST 123  Sunday   Evening      7054.0
Sunday Night
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3029  34 ST-HERALD SQ BDFMNQRW  Sunday     Night     10125.8
1  11394     JKSN HT-ROOSVLT 7EFMR  Sunday     Night      9163.6
2   9714           FLUSHING-MAIN 7  Sunday     Night      7755.4
3    929   14 ST-UNION SQ 456LNQRW  Sunday     Night      6587.4
4   6809              BEDFORD AV L  Sunday     Night      6087.4
Monday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    916   14 ST-UNION SQ 456LNQRW  Monday      Dawn     18857.2
1  10156        FULTON ST 2345ACJZ  Monday      Dawn     16119.4
2  13621            PATH NEW WTC 1  Monday      Dawn     14216.8
3   3016  34 ST-HERALD SQ BDFMNQRW  Monday      Dawn     11292.0
4   3471       47-50 STS ROCK BDFM  Monday      Dawn      9162.4
Monday Morning
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3018  34 ST-HERALD SQ BDFMNQRW  Monday   Morning     36516.4
1   3473       47-50 STS ROCK BDFM  Monday   Morning     35787.0
2  10158        FULTON ST 2345ACJZ  Monday   Morning     29509.4
3    918   14 ST-UNION SQ 456LNQRW  Monday   Morning     25359.0
4  13623            PATH NEW WTC 1  Monday   Morning     23726.0
Monday Afternoon
    index                STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3015  34 ST-HERALD SQ BDFMNQRW  Monday  Afternoon     20741.0
1    915   14 ST-UNION SQ 456LNQRW  Monday  Afternoon     19819.6
2  10155        FULTON ST 2345ACJZ  Monday  Afternoon     13152.2
3   3995      59 ST COLUMBUS 1ABCD  Monday  Afternoon     10069.2
4   5115                 86 ST 456  Monday  Afternoon      9306.6
Monday Evening
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3017  34 ST-HERALD SQ BDFMNQRW  Monday   Evening     30437.6
1    917   14 ST-UNION SQ 456LNQRW  Monday   Evening     19898.6
2   9702           FLUSHING-MAIN 7  Monday   Evening     18661.2
3   5817  ATL AV-BARCLAY 2345BDNQR  Monday   Evening     15935.0
4  11382     JKSN HT-ROOSVLT 7EFMR  Monday   Evening     14947.0
Monday Night
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11489            KEW GARDENS EF  Monday     Night      8994.4
1  11419          JOURNAL SQUARE 1  Monday     Night      7553.4
2  11384     JKSN HT-ROOSVLT 7EFMR  Monday     Night      7062.4
3   3019  34 ST-HERALD SQ BDFMNQRW  Monday     Night      6338.0
4   9704           FLUSHING-MAIN 7  Monday     Night      5967.0
Tuesday Dawn
    index                STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0    936   14 ST-UNION SQ 456LNQRW  Tuesday      Dawn     19611.0
1  10176        FULTON ST 2345ACJZ  Tuesday      Dawn     16686.4
2  13641            PATH NEW WTC 1  Tuesday      Dawn     14832.8
3   3036  34 ST-HERALD SQ BDFMNQRW  Tuesday      Dawn     10937.8
4   3491       47-50 STS ROCK BDFM  Tuesday      Dawn      9880.6
Tuesday Morning
    index                STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3038  34 ST-HERALD SQ BDFMNQRW  Tuesday   Morning     37246.8
1   3493       47-50 STS ROCK BDFM  Tuesday   Morning     36391.2
2  10178        FULTON ST 2345ACJZ  Tuesday   Morning     30071.2
3    938   14 ST-UNION SQ 456LNQRW  Tuesday   Morning     26145.8
4  13643            PATH NEW WTC 1  Tuesday   Morning     26078.0
Tuesday Afternoon
    index                STAT_MERGE  DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3035  34 ST-HERALD SQ BDFMNQRW  Tuesday  Afternoon     20681.6
1    935   14 ST-UNION SQ 456LNQRW  Tuesday  Afternoon     20002.2
2  10175        FULTON ST 2345ACJZ  Tuesday  Afternoon     13560.8
3   4015      59 ST COLUMBUS 1ABCD  Tuesday  Afternoon     10506.0
4   5135                 86 ST 456  Tuesday  Afternoon      9598.4
Tuesday Evening
    index                STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3037  34 ST-HERALD SQ BDFMNQRW  Tuesday   Evening     32779.4
1    937   14 ST-UNION SQ 456LNQRW  Tuesday   Evening     21404.8
2   9722           FLUSHING-MAIN 7  Tuesday   Evening     18809.0
3   5837  ATL AV-BARCLAY 2345BDNQR  Tuesday   Evening     15478.6
4  11402     JKSN HT-ROOSVLT 7EFMR  Tuesday   Evening     15105.8
Tuesday Night
    index                STAT_MERGE  DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11509            KEW GARDENS EF  Tuesday     Night      9958.4
1  11404     JKSN HT-ROOSVLT 7EFMR  Tuesday     Night      9467.2
2   9724           FLUSHING-MAIN 7  Tuesday     Night      9316.4
3   3039  34 ST-HERALD SQ BDFMNQRW  Tuesday     Night      8002.6
4  11439          JOURNAL SQUARE 1  Tuesday     Night      6944.4
Wednesday Dawn
    index                STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0    941   14 ST-UNION SQ 456LNQRW  Wednesday      Dawn     20026.4
1  10181        FULTON ST 2345ACJZ  Wednesday      Dawn     17401.8
2  13646            PATH NEW WTC 1  Wednesday      Dawn     14277.6
3   3041  34 ST-HERALD SQ BDFMNQRW  Wednesday      Dawn     10738.6
4   3496       47-50 STS ROCK BDFM  Wednesday      Dawn      9611.0
Wednesday Morning
    index                STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3043  34 ST-HERALD SQ BDFMNQRW  Wednesday   Morning     39634.4
1   3498       47-50 STS ROCK BDFM  Wednesday   Morning     36717.6
2  10183        FULTON ST 2345ACJZ  Wednesday   Morning     29535.4
3    943   14 ST-UNION SQ 456LNQRW  Wednesday   Morning     26395.0
4  13648            PATH NEW WTC 1  Wednesday   Morning     24504.0
Wednesday Afternoon
    index                STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3040  34 ST-HERALD SQ BDFMNQRW  Wednesday  Afternoon     23392.4
1    940   14 ST-UNION SQ 456LNQRW  Wednesday  Afternoon     21127.0
2  10180        FULTON ST 2345ACJZ  Wednesday  Afternoon     13620.8
3   4020      59 ST COLUMBUS 1ABCD  Wednesday  Afternoon     11561.2
4   3495       47-50 STS ROCK BDFM  Wednesday  Afternoon     10029.8
Wednesday Evening
    index                STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3042  34 ST-HERALD SQ BDFMNQRW  Wednesday   Evening     32807.6
1    942   14 ST-UNION SQ 456LNQRW  Wednesday   Evening     22304.0
2   9727           FLUSHING-MAIN 7  Wednesday   Evening     18741.8
3   5842  ATL AV-BARCLAY 2345BDNQR  Wednesday   Evening     15958.0
4  11407     JKSN HT-ROOSVLT 7EFMR  Wednesday   Evening     14925.0
Wednesday Night
    index                STAT_MERGE    DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11514            KEW GARDENS EF  Wednesday     Night     10503.6
1   9729           FLUSHING-MAIN 7  Wednesday     Night      9860.4
2  11409     JKSN HT-ROOSVLT 7EFMR  Wednesday     Night      9725.4
3   3044  34 ST-HERALD SQ BDFMNQRW  Wednesday     Night      9166.8
4  11444          JOURNAL SQUARE 1  Wednesday     Night      8569.2
Thursday Dawn
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0    931   14 ST-UNION SQ 456LNQRW  Thursday      Dawn     19391.6
1  10171        FULTON ST 2345ACJZ  Thursday      Dawn     16098.2
2  13636            PATH NEW WTC 1  Thursday      Dawn     14789.0
3   3031  34 ST-HERALD SQ BDFMNQRW  Thursday      Dawn     10586.2
4   3486       47-50 STS ROCK BDFM  Thursday      Dawn      9462.0
Thursday Morning
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3033  34 ST-HERALD SQ BDFMNQRW  Thursday   Morning     39724.6
1   3488       47-50 STS ROCK BDFM  Thursday   Morning     37089.0
2  10173        FULTON ST 2345ACJZ  Thursday   Morning     29627.2
3    933   14 ST-UNION SQ 456LNQRW  Thursday   Morning     25859.8
4  11923       LEXINGTON AV/53 6EM  Thursday   Morning     24489.4
Thursday Afternoon
    index                STAT_MERGE   DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3030  34 ST-HERALD SQ BDFMNQRW  Thursday  Afternoon     23971.4
1    930   14 ST-UNION SQ 456LNQRW  Thursday  Afternoon     21037.8
2  10170        FULTON ST 2345ACJZ  Thursday  Afternoon     14078.6
3   4010      59 ST COLUMBUS 1ABCD  Thursday  Afternoon     11252.0
4   3485       47-50 STS ROCK BDFM  Thursday  Afternoon     10343.8
Thursday Evening
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3032  34 ST-HERALD SQ BDFMNQRW  Thursday   Evening    34116.20
1    932   14 ST-UNION SQ 456LNQRW  Thursday   Evening    22757.75
2   9717           FLUSHING-MAIN 7  Thursday   Evening    16070.40
3   5832  ATL AV-BARCLAY 2345BDNQR  Thursday   Evening    15499.80
4  11397     JKSN HT-ROOSVLT 7EFMR  Thursday   Evening    15390.75
Thursday Night
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11399     JKSN HT-ROOSVLT 7EFMR  Thursday     Night     10266.2
1   9719           FLUSHING-MAIN 7  Thursday     Night      9965.8
2  11504            KEW GARDENS EF  Thursday     Night      9963.6
3   3034  34 ST-HERALD SQ BDFMNQRW  Thursday     Night      9847.0
4  11434          JOURNAL SQUARE 1  Thursday     Night      9026.8
Friday Dawn
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0    911   14 ST-UNION SQ 456LNQRW  Friday      Dawn     17895.4
1  10151        FULTON ST 2345ACJZ  Friday      Dawn     13843.6
2  13616            PATH NEW WTC 1  Friday      Dawn     11186.2
3   3011  34 ST-HERALD SQ BDFMNQRW  Friday      Dawn     10174.6
4   3466       47-50 STS ROCK BDFM  Friday      Dawn      7892.0
Friday Morning
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3013  34 ST-HERALD SQ BDFMNQRW  Friday   Morning     37422.6
1   3468       47-50 STS ROCK BDFM  Friday   Morning     33706.8
2  10153        FULTON ST 2345ACJZ  Friday   Morning     27431.4
3    913   14 ST-UNION SQ 456LNQRW  Friday   Morning     25212.4
4  11903       LEXINGTON AV/53 6EM  Friday   Morning     22282.6
Friday Afternoon
    index                STAT_MERGE DAYWEEK  TIMEOFDAY  ACTUALEXIT
0   3010  34 ST-HERALD SQ BDFMNQRW  Friday  Afternoon     25663.6
1    910   14 ST-UNION SQ 456LNQRW  Friday  Afternoon     21734.6
2  10150        FULTON ST 2345ACJZ  Friday  Afternoon     14542.8
3   5110                 86 ST 456  Friday  Afternoon     10595.6
4   3990      59 ST COLUMBUS 1ABCD  Friday  Afternoon     10532.2
Friday Evening
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3012  34 ST-HERALD SQ BDFMNQRW  Friday   Evening     32644.0
1    912   14 ST-UNION SQ 456LNQRW  Friday   Evening     22462.0
2   9697           FLUSHING-MAIN 7  Friday   Evening     17802.2
3   5812  ATL AV-BARCLAY 2345BDNQR  Friday   Evening     15761.0
4  11377     JKSN HT-ROOSVLT 7EFMR  Friday   Evening     14898.0
Friday Night
    index                STAT_MERGE DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11379     JKSN HT-ROOSVLT 7EFMR  Friday     Night    10675.75
1   3014  34 ST-HERALD SQ BDFMNQRW  Friday     Night    10216.20
2   9699           FLUSHING-MAIN 7  Friday     Night     8796.20
3   6794              BEDFORD AV L  Friday     Night     7609.00
4  11484            KEW GARDENS EF  Friday     Night     7336.80
Saturday Dawn
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0    921   14 ST-UNION SQ 456LNQRW  Saturday      Dawn      5131.6
1   3021  34 ST-HERALD SQ BDFMNQRW  Saturday      Dawn      3647.8
2   4491                 72 ST 123  Saturday      Dawn      2827.8
3   7781          CANAL ST 6JNQRWZ  Saturday      Dawn      2720.6
4   5401                 96 ST 123  Saturday      Dawn      2429.6
Saturday Morning
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0    923   14 ST-UNION SQ 456LNQRW  Saturday   Morning     16910.0
1   3023  34 ST-HERALD SQ BDFMNQRW  Saturday   Morning     14318.0
2   7783          CANAL ST 6JNQRWZ  Saturday   Morning     10023.2
3   4003      59 ST COLUMBUS 1ABCD  Saturday   Morning      9219.2
4   4493                 72 ST 123  Saturday   Morning      8632.2
Saturday Afternoon
    index                STAT_MERGE   DAYWEEK  TIMEOFDAY  ACTUALEXIT
0    920   14 ST-UNION SQ 456LNQRW  Saturday  Afternoon     20221.2
1   3020  34 ST-HERALD SQ BDFMNQRW  Saturday  Afternoon     19520.2
2   4000      59 ST COLUMBUS 1ABCD  Saturday  Afternoon      9946.4
3   7780          CANAL ST 6JNQRWZ  Saturday  Afternoon      9372.6
4  15480    W 4 ST-WASH SQ ABCDEFM  Saturday  Afternoon      9348.8
Saturday Evening
    index                STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0   3022  34 ST-HERALD SQ BDFMNQRW  Saturday   Evening     17796.0
1    922   14 ST-UNION SQ 456LNQRW  Saturday   Evening     15050.0
2   9707           FLUSHING-MAIN 7  Saturday   Evening      9108.8
3  11387     JKSN HT-ROOSVLT 7EFMR  Saturday   Evening      9087.0
4  15482    W 4 ST-WASH SQ ABCDEFM  Saturday   Evening      8812.4
Saturday Night
    index             STAT_MERGE   DAYWEEK TIMEOFDAY  ACTUALEXIT
0  11494         KEW GARDENS EF  Saturday     Night      3484.2
1  11389  JKSN HT-ROOSVLT 7EFMR  Saturday     Night      2986.2
2  10164     FULTON ST 2345ACJZ  Saturday     Night      2495.2
3   8379           CITY / BUS 1  Saturday     Night      2438.4
4  10514         GROVE STREET 1  Saturday     Night      2204.0

In [98]:
(grouped_means_nohubs
 .sort_values(by=['DAYWEEK','TIMEOFDAY', 'ACTUALEXIT'], ascending=[True,True,False])
 .groupby(['DAYWEEK','TIMEOFDAY'])
 .head())

                     STAT_MERGE    DAYWEEK  TIMEOFDAY  ACTUALEXIT
3010   34 ST-HERALD SQ BDFMNQRW     Friday  Afternoon    25663.60
910     14 ST-UNION SQ 456LNQRW     Friday  Afternoon    21734.60
10150        FULTON ST 2345ACJZ     Friday  Afternoon    14542.80
5110                  86 ST 456     Friday  Afternoon    10595.60
3990       59 ST COLUMBUS 1ABCD     Friday  Afternoon    10532.20
911     14 ST-UNION SQ 456LNQRW     Friday       Dawn    17895.40
10151        FULTON ST 2345ACJZ     Friday       Dawn    13843.60
13616            PATH NEW WTC 1     Friday       Dawn    11186.20
3011   34 ST-HERALD SQ BDFMNQRW     Friday       Dawn    10174.60
3466        47-50 STS ROCK BDFM     Friday       Dawn     7892.00
3012   34 ST-HERALD SQ BDFMNQRW     Friday    Evening    32644.00
912     14 ST-UNION SQ 456LNQRW     Friday    Evening    22462.00
9697            FLUSHING-MAIN 7     Friday    Evening    17802.20
5812   ATL AV-BARCLAY 2345BDNQR     Friday    Evening    15761.00
11377     JKSN HT-ROOSVLT 7EFMR     Friday    Evening    14898.00
3013   34 ST-HERALD SQ BDFMNQRW     Friday    Morning    37422.60
3468        47-50 STS ROCK BDFM     Friday    Morning    33706.80
10153        FULTON ST 2345ACJZ     Friday    Morning    27431.40
913     14 ST-UNION SQ 456LNQRW     Friday    Morning    25212.40
11903       LEXINGTON AV/53 6EM     Friday    Morning    22282.60
11379     JKSN HT-ROOSVLT 7EFMR     Friday      Night    10675.75
3014   34 ST-HERALD SQ BDFMNQRW     Friday      Night    10216.20
9699            FLUSHING-MAIN 7     Friday      Night     8796.20
6794               BEDFORD AV L     Friday      Night     7609.00
11484            KEW GARDENS EF     Friday      Night     7336.80
3015   34 ST-HERALD SQ BDFMNQRW     Monday  Afternoon    20741.00
915     14 ST-UNION SQ 456LNQRW     Monday  Afternoon    19819.60
10155        FULTON ST 2345ACJZ     Monday  Afternoon    13152.20
3995       59 ST COLUMBUS 1ABCD     Monday  Afternoon    10069.20
5115                  86 ST 456     Monday  Afternoon     9306.60
916     14 ST-UNION SQ 456LNQRW     Monday       Dawn    18857.20
10156        FULTON ST 2345ACJZ     Monday       Dawn    16119.40
13621            PATH NEW WTC 1     Monday       Dawn    14216.80
3016   34 ST-HERALD SQ BDFMNQRW     Monday       Dawn    11292.00
3471        47-50 STS ROCK BDFM     Monday       Dawn     9162.40
3017   34 ST-HERALD SQ BDFMNQRW     Monday    Evening    30437.60
917     14 ST-UNION SQ 456LNQRW     Monday    Evening    19898.60
9702            FLUSHING-MAIN 7     Monday    Evening    18661.20
5817   ATL AV-BARCLAY 2345BDNQR     Monday    Evening    15935.00
11382     JKSN HT-ROOSVLT 7EFMR     Monday    Evening    14947.00
3018   34 ST-HERALD SQ BDFMNQRW     Monday    Morning    36516.40
3473        47-50 STS ROCK BDFM     Monday    Morning    35787.00
10158        FULTON ST 2345ACJZ     Monday    Morning    29509.40
918     14 ST-UNION SQ 456LNQRW     Monday    Morning    25359.00
13623            PATH NEW WTC 1     Monday    Morning    23726.00
11489            KEW GARDENS EF     Monday      Night     8994.40
11419          JOURNAL SQUARE 1     Monday      Night     7553.40
11384     JKSN HT-ROOSVLT 7EFMR     Monday      Night     7062.40
3019   34 ST-HERALD SQ BDFMNQRW     Monday      Night     6338.00
9704            FLUSHING-MAIN 7     Monday      Night     5967.00
920     14 ST-UNION SQ 456LNQRW   Saturday  Afternoon    20221.20
3020   34 ST-HERALD SQ BDFMNQRW   Saturday  Afternoon    19520.20
4000       59 ST COLUMBUS 1ABCD   Saturday  Afternoon     9946.40
7780           CANAL ST 6JNQRWZ   Saturday  Afternoon     9372.60
15480    W 4 ST-WASH SQ ABCDEFM   Saturday  Afternoon     9348.80
921     14 ST-UNION SQ 456LNQRW   Saturday       Dawn     5131.60
3021   34 ST-HERALD SQ BDFMNQRW   Saturday       Dawn     3647.80
4491                  72 ST 123   Saturday       Dawn     2827.80
7781           CANAL ST 6JNQRWZ   Saturday       Dawn     2720.60
5401                  96 ST 123   Saturday       Dawn     2429.60
3022   34 ST-HERALD SQ BDFMNQRW   Saturday    Evening    17796.00
922     14 ST-UNION SQ 456LNQRW   Saturday    Evening    15050.00
9707            FLUSHING-MAIN 7   Saturday    Evening     9108.80
11387     JKSN HT-ROOSVLT 7EFMR   Saturday    Evening     9087.00
15482    W 4 ST-WASH SQ ABCDEFM   Saturday    Evening     8812.40
923     14 ST-UNION SQ 456LNQRW   Saturday    Morning    16910.00
3023   34 ST-HERALD SQ BDFMNQRW   Saturday    Morning    14318.00
7783           CANAL ST 6JNQRWZ   Saturday    Morning    10023.20
4003       59 ST COLUMBUS 1ABCD   Saturday    Morning     9219.20
4493                  72 ST 123   Saturday    Morning     8632.20
11494            KEW GARDENS EF   Saturday      Night     3484.20
11389     JKSN HT-ROOSVLT 7EFMR   Saturday      Night     2986.20
10164        FULTON ST 2345ACJZ   Saturday      Night     2495.20
8379               CITY / BUS 1   Saturday      Night     2438.40
10514            GROVE STREET 1   Saturday      Night     2204.00
925     14 ST-UNION SQ 456LNQRW     Sunday  Afternoon    16447.20
3025   34 ST-HERALD SQ BDFMNQRW     Sunday  Afternoon    16321.40
4005       59 ST COLUMBUS 1ABCD     Sunday  Afternoon     9108.00
4495                  72 ST 123     Sunday  Afternoon     9036.80
7785           CANAL ST 6JNQRWZ     Sunday  Afternoon     8116.80
926     14 ST-UNION SQ 456LNQRW     Sunday       Dawn     3133.60
3026   34 ST-HERALD SQ BDFMNQRW     Sunday       Dawn     2340.60
4496                  72 ST 123     Sunday       Dawn     2049.00
7786           CANAL ST 6JNQRWZ     Sunday       Dawn     1865.60
5406                  96 ST 123     Sunday       Dawn     1785.40
3027   34 ST-HERALD SQ BDFMNQRW     Sunday    Evening    14437.00
927     14 ST-UNION SQ 456LNQRW     Sunday    Evening    11071.80
11392     JKSN HT-ROOSVLT 7EFMR     Sunday    Evening     7962.60
9712            FLUSHING-MAIN 7     Sunday    Evening     7651.00
5407                  96 ST 123     Sunday    Evening     7054.00
928     14 ST-UNION SQ 456LNQRW     Sunday    Morning    12255.40
3028   34 ST-HERALD SQ BDFMNQRW     Sunday    Morning    10862.00
7788           CANAL ST 6JNQRWZ     Sunday    Morning     8742.20
4498                  72 ST 123     Sunday    Morning     7111.80
15488    W 4 ST-WASH SQ ABCDEFM     Sunday    Morning     6663.60
3029   34 ST-HERALD SQ BDFMNQRW     Sunday      Night    10125.80
11394     JKSN HT-ROOSVLT 7EFMR     Sunday      Night     9163.60
9714            FLUSHING-MAIN 7     Sunday      Night     7755.40
929     14 ST-UNION SQ 456LNQRW     Sunday      Night     6587.40
6809               BEDFORD AV L     Sunday      Night     6087.40
3030   34 ST-HERALD SQ BDFMNQRW   Thursday  Afternoon    23971.40
930     14 ST-UNION SQ 456LNQRW   Thursday  Afternoon    21037.80
10170        FULTON ST 2345ACJZ   Thursday  Afternoon    14078.60
4010       59 ST COLUMBUS 1ABCD   Thursday  Afternoon    11252.00
3485        47-50 STS ROCK BDFM   Thursday  Afternoon    10343.80
931     14 ST-UNION SQ 456LNQRW   Thursday       Dawn    19391.60
10171        FULTON ST 2345ACJZ   Thursday       Dawn    16098.20
13636            PATH NEW WTC 1   Thursday       Dawn    14789.00
3031   34 ST-HERALD SQ BDFMNQRW   Thursday       Dawn    10586.20
3486        47-50 STS ROCK BDFM   Thursday       Dawn     9462.00
3032   34 ST-HERALD SQ BDFMNQRW   Thursday    Evening    34116.20
932     14 ST-UNION SQ 456LNQRW   Thursday    Evening    22757.75
9717            FLUSHING-MAIN 7   Thursday    Evening    16070.40
5832   ATL AV-BARCLAY 2345BDNQR   Thursday    Evening    15499.80
11397     JKSN HT-ROOSVLT 7EFMR   Thursday    Evening    15390.75
3033   34 ST-HERALD SQ BDFMNQRW   Thursday    Morning    39724.60
3488        47-50 STS ROCK BDFM   Thursday    Morning    37089.00
10173        FULTON ST 2345ACJZ   Thursday    Morning    29627.20
933     14 ST-UNION SQ 456LNQRW   Thursday    Morning    25859.80
11923       LEXINGTON AV/53 6EM   Thursday    Morning    24489.40
11399     JKSN HT-ROOSVLT 7EFMR   Thursday      Night    10266.20
9719            FLUSHING-MAIN 7   Thursday      Night     9965.80
11504            KEW GARDENS EF   Thursday      Night     9963.60
3034   34 ST-HERALD SQ BDFMNQRW   Thursday      Night     9847.00
11434          JOURNAL SQUARE 1   Thursday      Night     9026.80
3035   34 ST-HERALD SQ BDFMNQRW    Tuesday  Afternoon    20681.60
935     14 ST-UNION SQ 456LNQRW    Tuesday  Afternoon    20002.20
10175        FULTON ST 2345ACJZ    Tuesday  Afternoon    13560.80
4015       59 ST COLUMBUS 1ABCD    Tuesday  Afternoon    10506.00
5135                  86 ST 456    Tuesday  Afternoon     9598.40
936     14 ST-UNION SQ 456LNQRW    Tuesday       Dawn    19611.00
10176        FULTON ST 2345ACJZ    Tuesday       Dawn    16686.40
13641            PATH NEW WTC 1    Tuesday       Dawn    14832.80
3036   34 ST-HERALD SQ BDFMNQRW    Tuesday       Dawn    10937.80
3491        47-50 STS ROCK BDFM    Tuesday       Dawn     9880.60
3037   34 ST-HERALD SQ BDFMNQRW    Tuesday    Evening    32779.40
937     14 ST-UNION SQ 456LNQRW    Tuesday    Evening    21404.80
9722            FLUSHING-MAIN 7    Tuesday    Evening    18809.00
5837   ATL AV-BARCLAY 2345BDNQR    Tuesday    Evening    15478.60
11402     JKSN HT-ROOSVLT 7EFMR    Tuesday    Evening    15105.80
3038   34 ST-HERALD SQ BDFMNQRW    Tuesday    Morning    37246.80
3493        47-50 STS ROCK BDFM    Tuesday    Morning    36391.20
10178        FULTON ST 2345ACJZ    Tuesday    Morning    30071.20
938     14 ST-UNION SQ 456LNQRW    Tuesday    Morning    26145.80
13643            PATH NEW WTC 1    Tuesday    Morning    26078.00
11509            KEW GARDENS EF    Tuesday      Night     9958.40
11404     JKSN HT-ROOSVLT 7EFMR    Tuesday      Night     9467.20
9724            FLUSHING-MAIN 7    Tuesday      Night     9316.40
3039   34 ST-HERALD SQ BDFMNQRW    Tuesday      Night     8002.60
11439          JOURNAL SQUARE 1    Tuesday      Night     6944.40
3040   34 ST-HERALD SQ BDFMNQRW  Wednesday  Afternoon    23392.40
940     14 ST-UNION SQ 456LNQRW  Wednesday  Afternoon    21127.00
10180        FULTON ST 2345ACJZ  Wednesday  Afternoon    13620.80
4020       59 ST COLUMBUS 1ABCD  Wednesday  Afternoon    11561.20
3495        47-50 STS ROCK BDFM  Wednesday  Afternoon    10029.80
941     14 ST-UNION SQ 456LNQRW  Wednesday       Dawn    20026.40
10181        FULTON ST 2345ACJZ  Wednesday       Dawn    17401.80
13646            PATH NEW WTC 1  Wednesday       Dawn    14277.60
3041   34 ST-HERALD SQ BDFMNQRW  Wednesday       Dawn    10738.60
3496        47-50 STS ROCK BDFM  Wednesday       Dawn     9611.00
3042   34 ST-HERALD SQ BDFMNQRW  Wednesday    Evening    32807.60
942     14 ST-UNION SQ 456LNQRW  Wednesday    Evening    22304.00
9727            FLUSHING-MAIN 7  Wednesday    Evening    18741.80
5842   ATL AV-BARCLAY 2345BDNQR  Wednesday    Evening    15958.00
11407     JKSN HT-ROOSVLT 7EFMR  Wednesday    Evening    14925.00
3043   34 ST-HERALD SQ BDFMNQRW  Wednesday    Morning    39634.40
3498        47-50 STS ROCK BDFM  Wednesday    Morning    36717.60
10183        FULTON ST 2345ACJZ  Wednesday    Morning    29535.40
943     14 ST-UNION SQ 456LNQRW  Wednesday    Morning    26395.00
13648            PATH NEW WTC 1  Wednesday    Morning    24504.00
11514            KEW GARDENS EF  Wednesday      Night    10503.60
9729            FLUSHING-MAIN 7  Wednesday      Night     9860.40
11409     JKSN HT-ROOSVLT 7EFMR  Wednesday      Night     9725.40
3044   34 ST-HERALD SQ BDFMNQRW  Wednesday      Night     9166.80
11444          JOURNAL SQUARE 1  Wednesday      Night     8569.20